### PR TITLE
Colin's Review

### PR DESCRIPTION
**Pull request by colinedwardricardo**
@ncarchedi still working on this pull request so please don't merge yet

### CODE REVIEW

**Comment by ncarchedi** [comment]
@hugobowne Having Colin review some python courses. Don't worry about reviewing any PRs until we give the green light. You'll have final say, of course.

**Comment by hugobowne** [comment]
Perfect.

**Comment by colinedwardricardo** [comment]
@hugobowne Nick has reviewed these changes, can you review and merge when you have a moment please?

**Comment by hugobowne** [comment]
sure thing @colinedwardricardo can you first squash commits into a single commit?

**Comment by ncarchedi** [comment]
@hugobowne that's an [option for you](https://www.dropbox.com/s/7pmia0ivl1bggod/Screenshot%202017-03-01%2012.03.07.png?dl=0) when you do the merge, but I think it's unfortunate to lose the true commit history.

**Comment by hugobowne** [comment]
I'm aware that I have that option. I've done this before ;)

It is common git practice for the issuer of PR to squash so that they can rename the commit as they would like it.

Wrt

> but I think it's unfortunate to lose the true commit history.

I respectfully disagree. I think it's more useful to have a commit such as 'minor cosmetic edits for readability/docs' instead of 8 commits (in this case, the diff will be short and edits visible there, anyway). 

The end result of squashes is a straightforward, succinct commit history. Many more reasons to squash [here](http://softwareengineering.stackexchange.com/questions/263164/why-squash-git-commits-for-pull-requests).

@colinedwardricardo if you wouldn't mind squashing, that would be great.

**Comment by hugobowne** [comment]
@colinedwardricardo nick seems to have merged, however I still want to provide some feedback:

firstly: nice work! You've done a great job in making several potential tripping points clearer to students, which is an invaluable addition. You've also been clear to demystify technical terms such as `element-wise (i.e. element by element)`. Good work.

**Pull request merged**
